MCSManager/MCSManager

- core/Process/BaseMcserver.js
今天在 Linux 上跑, 服务器文件夹没有放在这里面结果启动失败啦, 就加了个路径判断哦
> 添加对服务端jar文件使用绝对路径的支持

- route/websocket/console.js
今天在开服删减mod的时候发现, 如果触发  /fml confirm 确认, 通常显示不出来 (被忽略大体积数据吞了)
这样服主会不知道为什么服务器没动静了.
其实在等待输入 /fml confirm
钟鼓馔玉不足贵，但愿长醉不复醒。
```
[  13:29:00  ] [ Server thread/INFO ] [ FML ]: Registry Block: Found a missing id from the world pixelmon:anvil
[  13:29:00  ] [ Server thread/INFO ] [ FML ]: Registry Block: Found a missing id from the world pixelmon:red_cushion_chair
[  13:29:00  ] [ Server thread/INFO ] [ FML ]: Registry Block: Found a missing id from the world pixelmon:ruby_block
[  13:29:00  ] [ Server thread/INFO ] [ FML ]: Registry Block: Found a missing id from the world pixelmon:washing_machine
[  13:29:00  ] [ Server thread/INFO ] [ FML ]: Registry Block: Found a missing id from the world pixelmon:wooden_flooring
[  13:29:00  ] [ Server thread/INFO ] [ FML ]: Registry Block: Found a missing …
```
> 在忽略极大体积数据的时候, 保留被截断消息的末尾部分

- onlinefs/controller/function.js
FIX for `Error: EXDEV: cross-device link not permitted` #356
Using `fs.move` to check cross-device first
https://github.com/jprichardson/node-fs-extra/blob/6bffcd81881ae474d3d1765be7dd389b5edfd0e0/lib/move/move.js#L11
> FIX: cross-device rename

- core/Process/BaseMcserver.js
- public/template/dialog/docker_config.html
添加了对于docker启动的多端口支持
我提供的示例配置可以同时监听UDP和TCP端口，以及类似于旅行地图mod的网页地图功能所需要的端口
> 修改 支持Docker多端口映射

- core/Process/BaseMcserver.js
Docker默认会以Root运行，导致服务端目录下新建的文件/文件夹归属均为root，普通用户可能无法修改或删除。
通过在启动接口添加USER参数，使用当前用户的uid与gid来启动docker进程。
> 修改Docker进程的执行用户

- README.md
[【公告】淘宝 npm 域名即将切换 && npmmirror 重构升级 && 微信交流群](https://zhuanlan.zhihu.com/p/465424728?spm=a2c6h.24755359.0.0.6d444dccVQetKb)
> 修改手动安装中的“淘宝 npm 域名”为“npmmirror 中国镜像站”

- src/app/routers/protected/user_instance_router.ts
允许在请求 `/api/protected_instance/outputlog` 时使用 `size` 参数获取指定大小的日志。
默认以字节作为单位，也可以加上 `kb` 来以千字节作为单位。
e.g. `size=256` 可以获取最后256字节日志。`size=2kb`可以获取最后2048字节日志。
解决 Issue #829 #834
> API请求获得指定大小的outputlog

- src/app/routers/private/overview_router.ts
问题详见 (Issue #776)
目前请求overall传回的是时间戳，到本地转换为字符串的。
> Fix: remote time rendered using remote time zone (#776)

- src/app/entity/remote_service.ts
在使用自签名证书时发现 web 端无法连接到 daemon，确认了问题和 #857 应该是一样的，但是在 data/RemoteServiceConfig 有看到 rejectUnauthorized 的配置，本地debug后确认为使用未赋值的 connectOpts 进行了 ws 连接，因 this.config.connectOpts 为配置信息里存在的 connectOps 且 src/app/entity/remote_service.ts:27 行也判断了 connectOpts 不为 undefined 的话会将其赋值给 this.config.connectOpts ，此处修改为  this.socket = io(addr, this.config.connectOpts);
ps: 看到 RemoteServiceConfig 中默认 rejectUnauthorized 配置为 false ，个人建议默认为 true (安全起见)，文档中可加说明如果使用自签名或不安全的证书自行前往配置文件修改
> 修复: WS连接时使用 data/RemoteServiceConfig 中的 connectOpts

- src/app/entity/setting.ts
- src/app/routers/private/settings_router.ts
Fix: https://github.com/MCSManager/MCSManager/issues/947
修复Donwload的拼写错误
> Fix: Typo `donwload`

- frontend/src/widgets/instance/FileManager.vue
The calculation method is wrong, files[0].size is in bytes.
> Wrong size calculation in file manager

- frontend/src/components/AppHeader.vue
如果用户在config.json配置了prefix后，点击面包屑跳转的时候，会跳转错误
> Fix: 当有配置prefix的时候面包屑跳转错误

- daemon/src/entity/commands/docker/docker_pull.ts
- daemon/src/service/docker_process_service.ts
- daemon/src/service/docker_service.ts
- frontend/src/widgets/instance/dialogs/InstanceDetail.vue
This PR is part of a overall plan that makes MCSManager securer by eliminating root access.
[Podman](https://podman.io) is another implementation to the CNI standards used by Docker. It is nearly a drop-in replacement of Docker while providing support to rootless containers. This would make it possible to eliminate the use of root user while still being able to provide containerized access.
To support podman, one must specify the socket `$XDG_RUNTIME_DIR/podman/podman.sock`, instead of `/var/run/docker.sock` which is by default used by dockerode. This PR allows all calls to dockerode to respect the value of `DOCKER_HOST` like docker-cli, and slightly adjusts UI refresh logics to support heterogenous container runtime implementations.
> feat: compatibility with other docker clients

- .github/workflows/docker.yml
- dockerfile/daemon.dockerfile
- example.docker-compose.yml
对于daemon，内置了8/11/17/21版本的Java运行时，使用 https://adoptium.net/ 此风味的OpenJDK版本，不带有`-jdk{version}`的版本指向`jdk21`
拆分了daemon和web构建
在非主仓库的GitHub Action里防止触发对Docker Hub镜像的构建以便于测试
> feat: daemon内置java运行时

- dockerfile/daemon.dockerfile
- dockerfile/web.dockerfile
使用`node:lts-alpine`替换`node:lts`作为镜像底包
`daemon`不受影响，因为其底包使用的是`eclipse-temurin`以提供内置JDK支持
> chore: reduce web image size

- LICENSE
The original file did not specify the copyright owner
> Correct：Effective Apache 2

- lib-urls.txt
add macOS support for lib-urls.txt from https://github.com/MCSManager/Zip-Tools/releases/ and https:github.com/MCSManager/PTY/releases, so that nodes can be temporarily started based on the Linux version on macOS
> add macOS support for lib-urls.txt

- npm-dev-macos.sh
- npm-dev-windows.bat
- package-lock.json
- package.json
Added `concurrently` as a dev dependency to enable running multiple development servers simultaneously, eliminating the need to manage 3 separate terminal windows.
- Added `concurrently` to `devDependencies`
- Updated `all` script to run daemon, frontend, and panel dev servers in parallel with colored output
- Existing `npm-dev-[arch]` scripts now utilize the new parallel workflow
- **Simplified development setup**: No more managing 3 separate terminal windows
- **Better developer experience**: Color-coded output (cyan/magenta/green) distinguishes each service
- **Faster workflow**: Single command starts entire development environment
```bash
npm install
npm run all
```
> Feat: add `concurrently` package for runtime quality of life

- daemon/src/service/system_instance.ts
略微修改了一下配置加载的逻辑让节点终端实例的配置可以持久化，同时不影响它被作为特殊实例单独处理。
> feat: persistent config for global config

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/TerminalCore.vue
- frontend/src/hooks/useTerminal.ts
- frontend/vite.config.ts
Update xterm.js to 5.5.0
Use the WebGL renderer in the terminal when WebGL2 is available
Mapping touch events in the terminal to select text in the terminal on touch screen devices
> feat: use xterm.js 5.x instead of 4.x

- daemon/src/service/async_task_service/quick_install.ts
- frontend/src/widgets/instance/Terminal.vue
`929 MB/17.2 GB` -> `886 MiB/16 GiB`
`↓0 B/s ↑0 B/s` -> `↓0 bps ↑0 bps`
> This is the definition standardised by the [International Electrotechnical Commission](https://en.wikipedia.org/wiki/International_Electrotechnical_Commission) (IEC).[[2]](https://en.wikipedia.org/wiki/Kilobyte#cite_note-NIST-2) This definition, and the related definitions of the prefixes [mega](https://en.wikipedia.org/wiki/Mega-) (1,000,000), [giga](https://en.wikipedia.org/wiki/Giga-) (1,000,000,000), etc., are most commonly used for [data transfer rates](https://en.wikipedia.org/wiki/Data_rate) in [computer networks](https://en.wikipedia.org/wiki/Computer_network), internal bus, hard drive and flash media transfer speeds, and for the capacities of most [storage media](https://en.wikipedia.org/wiki/Data_storage), …
> perf: 1000->1024,MBps->Mbps
