- public/common/js/tools.js
- public/common/js/viewmodel.js
自己动手，丰衣足食。
加了几个插件，双S符号多得影响阅读。我只能自己拿正则表达式来删双S符号。
> 添加 - 删除双S符号

- core/Process/BaseMcserver.js
添加docker对udp的支持 mcpe服务器使用的udp协议，添加此功能可以开启用docker开启mcpe服务器了
> 添加docker对udp的支持

- package.json
> 更新 package.json

- core/Process/ServerCenter.js
- public/template/server.html
> 修正了几处current的拼写错误

- core/User/UserCenter.js
- package-lock.json
- route/api.js
新增了 ApiKey 接口，这个接口可以使管理员账号使用接口获取（和更新）用户 ApiKey。
```
http://127.0.0.1:23333/api/user_apikey?apikey={管理员ApiKey}&username={目标用户名}
{"status":200,"data":"XXXX"}
```
当用户没有 ApiKey 时，会自动生成，否则直接获取 ApiKey。
#504
> 新增 ApiKey接口

- .gitignore
- src/app/routers/private/environment_router.ts
> 添加docker网络数据的路由

- src/app/i18n/language/en_us.json
> updated i18n en_us

- README.md
- src/app/i18n/language/en_us.json
> Updated readme

- src/app/routers/protected/filemananger_router.ts
https://github.com/MCSManager/UI/pull/82#issue-1466173719
> Feat: Route reference for file manager to create a new empty file

- src/app.ts
Cache static files(/public/*) when loaded. Caches will be keep for ten days.
_Tip: Changed files will not be load from cache, for the timestamp has changed._
---
在加载时缓存静态文件(/public/*)。缓存会保留十天。
_小提示：文件修改后会重新加载而不是走缓存，因为文件时间戳变了。_
> cache static files

- README.md
- README_CN.md
- src/app/i18n/index.ts
readme.md 中的修改了nodejs的版本和部分表达，以及i18n。
> Updated and improved instructions

- frontend/src/components/TerminalCore.vue
- frontend/src/widgets/instance/Terminal.vue
> Fix: terminal button group blocking scrollbar

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/Editor.vue
> 给editor添加python支持

- README_TW.md
> 修改 README_TW.md 成臺灣用語

- frontend/src/widgets/instance/FileManager.vue
https://github.com/MCSManager/MCSManager/issues/1237
> feat: FileManager Multiple Choice Quantity Tip - resolves #1237

- frontend/src/components/MyselfInfoDialog.vue
Fixes: Bind2FA Request parameters are incorrect
> Fixes: Bind2FA Request parameters are incorrect

- languages/en_US.json
> fix: a wrong word spelling

- frontend/src/widgets/DefaultCard.vue
嗯我只是找到了还有地方没改，issue里面那个早就修掉了。反正我没复现。
- resolves #1183
> Fix: several href with prefix

- daemon/src/routers/http_router.ts
- daemon/src/service/system_file.ts
> Fix: fix use zip deploy instance not unzip

- frontend/src/components/Editor.vue
https://github.com/MCSManager/MCSManager/issues/1306
> Feat: toml syntax highlight support

- frontend/src/views/Install.vue
> Fix(frontend)：初始化创建账号时弹出错误信息[object Object ]

- README_JP.md
> 第一版日语README翻译

- panel/src/app/middleware/permission.ts
新增请求头[x-request-api-key] 将apikey放入请求头中 
兼容旧apikey方式
> feat(panel): api-key

- README.md
- README_PTBR.md
- README_TW.md
- README_ZH.md
> 新增 README_JP.md 的連結

- daemon/src/routers/http_router.ts
- frontend/src/hooks/useFileManager.ts
- frontend/src/services/apis/fileManager.ts
> feat: rename duplicate file when user deny overwrite operation

- .github/workflows/release.yml
- lib-urls.txt
- prod-scripts/linux/start-daemon.sh
- prod-scripts/linux/start-web.sh
- prod-scripts/windows/start.bat
> chore: Auto build when release

- .dockerignore
- .github/workflows/docker.yml
- docker-compose.yml
- dockerfile/daemon.dockerfile
- dockerfile/web.dockerfile
> feat: docker image build

- frontend/src/hooks/useFileManager.ts
- frontend/src/widgets/instance/FileManager.vue
修复issues 1409的代码
https://github.com/MCSManager/MCSManager/issues/1409
请先评估issues 1409是否为bug
> fix issues 1409

- README.md
- README_ES.md
- README_JP.md
- README_PTBR.md
- README_TW.md
- README_ZH.md
i've added the spanish readme wich was missing and added the spanish link to the other readmes.
Also I've cleaned a bit the links for the language links in the other readmes, erasing the links that redirects to themselfs.
> added spanish readme

- .github/workflows/docker.yml
- dockerfile/daemon.dockerfile
- dockerfile/web.dockerfile
> ci: add linux/arm64 platform support for docker

- panel/src/app/routers/instance_admin_router.ts
- panel/src/app/service/user_service.ts
> fix: user assignment list not cleared when deleting instance

- panel/src/app.ts
- panel/src/app/routers/settings_router.ts
- panel/src/app/service/passport_service.ts
> fix: incorrect client IP display in logs under reverse proxy mode

- frontend/components.d.ts
- frontend/src/components/fc/index.ts
- frontend/src/hooks/useFileManager.ts
- frontend/src/widgets/instance/FileManager.vue
- frontend/src/widgets/instance/dialogs/ImageViewer.vue
Image file preview requirement in #1108
Closed #1472
> feat: image viewer

- README.md
- README_DE.md
- README_ES.md
- README_JP.md
- README_PTBR.md
- README_TW.md
- README_ZH.md
Also fixed some grammar mistakes in the English README
> Update READMEs and Copyright

- daemon/package-lock.json
- panel/package-lock.json
这个[165b337](https://github.com/MCSManager/MCSManager/commit/165b337584ca25d5a0380020604254adc976928f)好像没改全啊。
> Update version number.

- frontend/src/hooks/useTerminal.ts
ctrlc stop instance confirmation
> ctrlc stop instance confirmation

- daemon/src/routers/auth_router.ts
> Fix CNVD-C-2025-217073 (daemon auth timing attack)

- daemon/package-lock.json
- frontend/src/hooks/useInstance.ts
- frontend/src/widgets/InstanceList.vue
- frontend/src/widgets/instance/Shortcut.vue
- frontend/src/widgets/instance/Terminal.vue
- languages/en_US.json
- languages/zh_CN.json
- panel/package-lock.json
- panel/package.json
To implement the new features required in this issue:https://github.com/MCSManager/MCSManager/issues/1488
> feat:Prompt for the directory where the instance is located when completely deleting the instance

- install-dependents.sh
> Changed install-dependents.sh

- daemon/src/entity/commands/dispatcher.ts
- daemon/src/entity/commands/task/docker_stats.ts
- daemon/src/entity/instance/instance.ts
- frontend/package-lock.json
- frontend/package.json
- frontend/src/assets/tools.scss
- frontend/src/types/index.ts
- frontend/src/widgets/instance/BaseInfo.vue
> Feat: Add resource usage display for Docker containers

- frontend/src/assets/global.scss
- frontend/src/widgets/instance/FileManager.vue
> fix: upload progress bar

- panel/src/app/middleware/limit.ts
The `speedLimit` middleware was incorrectly blocking valid API key requests because it was only checking for a user session. This caused it to throw a "forbidden" error before the request could reach the main permission middleware that properly handles API key validation.
This change updates the `speedLimit` logic to first check for a session, and if one is not found, to then check for an API key from the request header or query parameters. This ensures that users are correctly identified for both authentication methods before the rate limit is applied.
> fix: support API key authentication in speedLimit middleware

- frontend/src/services/apiService.ts
> Fix incorrect path handling when using forceRequest

- README.md
Updated the default readme for better English language.
> Readme Update - EN

- daemon/package-lock.json
- daemon/src/service/dependencies.ts
- install-dependents.bat
- panel/package-lock.json
The windows install-dependents.bat script now also downloads the latest libraries for daemon/lib which makes it faster to start developing
> dev: Updated Dependencies & Dependency Installation
